### ISSUE TITLE
Create game board

### ISSUE THREAD

**Issue by paulakaferreira** [paulakaferreira/scrabble#3]
Design and create the scrabble game board.
The game board is of size 15x15.

**Comment by lucaslrx** [comment]
The game board must be a two dimensional array. We should define a constant which would correspond to both the rows and the columns of the array.
I haven't figured out yet how to manage special squares on the board (triple word, tripple letter square)

**Comment by paulakaferreira** [comment]
I'm mentally trying to figure it out, but haven't tried it yet.

**Comment by paulakaferreira** [comment]
Created board logic on 26/12. Waiting for pull request to be accepted. Board logic still needs to be changed to include game details such as:
- Case value;
- The priting of the index for each row and column;
- word validation (a function that reads the word the player wants to create).
